name: Python package

on:
  push:
    branches: [ "main" ]
    tags: 
      - "release-*"
      - "beta-*"
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    # This job only runs in the context of your 'pypi' environment
    environment: pypi 
    permissions:
      id-token: write # Mandatory for Trusted Publishing
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python 3.12
      run: uv python install 3.12

    - name: Build
      run: uv build

    - name: Publish to PyPI
      # Secure check to ensure only authorized tags trigger the upload
      if: |
        github.event_name == 'push' && 
        (startsWith(github.ref, 'refs/tags/release-') || startsWith(github.ref, 'refs/tags/beta-'))
      run: uv publish
